# Generated by Django 4.2.16 on 2025-01-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_name_profile_first_name_profile_last_name'),
        ('dchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='created_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chats_received', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chats_created', to='user.profile'),
        ),
    ]
